#ifndef FARMER_CONSTANTS_H
#define FARMER_CONSTANTS_H

#define INVENTORY_SIZE 10
#define INPUT_BUFFER_SIZE 128
#define INPUT_BASE 10
#define HOURS_PER_DAY 24
#define MINUTES_AT_HOUR 0
#define MIN_WORK_HOURS 1

#define STARTING_DAY 1
#define STARTING_HOUR 8

#define SLOT_FIRST 0
#define SLOT_LAST (INVENTORY_SIZE - 1)

#define ITEM_EMPTY 0
#define ITEM_TREE 1
#define ITEM_STONE 2
#define ITEM_SEEDS 3
#define ITEM_CARROT 4
#define ITEM_APPLE 5
#define ITEM_FIBER 6
#define ITEM_IRON_ORE 7
#define ITEM_FISH 8
#define ITEM_MILK 9
#define ITEM_ID_MIN ITEM_EMPTY
#define ITEM_ID_MAX ITEM_MILK

#define MENU_EXIT 0
#define MENU_SHOW_TIME 1
#define MENU_WORK 2
#define MENU_SHOW_INVENTORY 3
#define MENU_PLACE_ITEM 4
#define MENU_DROP_ITEM 5
#define MENU_VARIANT_TASK 6

#define START_SLOT_TREE_FIRST SLOT_FIRST
#define START_SLOT_STONE 2
#define START_SLOT_SEEDS 3
#define START_SLOT_CARROT 5
#define START_SLOT_TREE_SECOND 6
#define START_SLOT_FIBER 8

#endif
